openapi: 3.0.0
info:
  title: Event Management System API
  description: API for managing events, including creating, updating, retrieving, and deleting events.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/events:
    get:
      summary: Get all events
      responses:
        200:
          description: List of all events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        500:
          description: Error fetching events
    post:
      summary: Create a new event
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                eventtimestamp:
                  type: string
                  format: date-time
                venue:
                  type: string
                image:
                  type: string
                  format: binary
                category:
                  type: string
                noparticipants:
                  type: integer
      responses:
        201:
          description: Event created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        500:
          description: Error creating event

  /api/events/{id}:
    put:
      summary: Update an event
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                eventtimestamp:
                  type: string
                  format: date-time
                venue:
                  type: string
                image:
                  type: string
                  format: binary
                category:
                  type: string
                noparticipants:
                  type: integer
      responses:
        200:
          description: Event updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        404:
          description: Event not found
        500:
          description: Error updating event

    delete:
      summary: Delete an event
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Event deleted successfully
        404:
          description: Event not found
        500:
          description: Error deleting event

components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        eventtimestamp:
          type: string
          format: date-time
        venue:
          type: string
        image:
          type: string
        category:
          type: string
        noparticipants:
          type: integer
        timestamp:
          type: string
          format: date-time
